"""Crea comps_transacciones si no existe, y la migra si existe con esquema antiguo."""
import os, sys
from urllib.parse import urlparse
from dotenv import load_dotenv
import pg8000

load_dotenv()
url = os.environ.get("DATABASE_URL")
if not url:
    sys.exit("DATABASE_URL no configurada")

p = urlparse(url)
conn = pg8000.connect(
    user=p.username, password=p.password,
    host=p.hostname, port=p.port or 5432,
    database=p.path.lstrip("/"), ssl_context=True,
)
conn.autocommit = False
cur = conn.cursor()

steps = [
    ("CREATE TABLE IF NOT EXISTS", """
CREATE TABLE IF NOT EXISTS comps_transacciones (
    id               BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comps_uid        TEXT         NOT NULL,
    consumo_id       TEXT         NOT NULL,
    fecha_jornada    DATE         NOT NULL,
    cliente_id       TEXT,
    nombre_cliente   TEXT,
    descripcion_cat  TEXT,
    descripcion_prod TEXT,
    micros           NUMERIC(12,0),
    estado           TEXT,
    usuario_id       TEXT,
    nombre_usuario   TEXT,
    archivo_origen   TEXT,
    created_at       TIMESTAMPTZ  DEFAULT NOW()
)
"""),
    ("ADD UNIQUE comps_uid", """
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint
    WHERE conrelid = 'comps_transacciones'::regclass AND contype = 'u'
      AND conname = 'comps_transacciones_comps_uid_key') THEN
    ALTER TABLE comps_transacciones
      ADD CONSTRAINT comps_transacciones_comps_uid_key UNIQUE (comps_uid);
  END IF;
END $$
"""),
    ("CREATE INDEX fecha_jornada",
     "CREATE INDEX IF NOT EXISTS idx_comps_jornada ON comps_transacciones (fecha_jornada DESC)"),
]

try:
    for label, sql in steps:
        print(f"  --> {label}")
        cur.execute(sql.strip())
    conn.commit()
    print("OK – tabla comps_transacciones lista")
except Exception as e:
    conn.rollback()
    print(f"ERROR: {e}")
    sys.exit(1)
finally:
    cur.close()
    conn.close()
