-- Migración no destructiva para comps_transacciones
-- Agrega columnas faltantes y convierte fecha_jornada a DATE preservando datos.

BEGIN;

-- 1) Agregar columnas faltantes
ALTER TABLE comps_transacciones
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS comps_uid     TEXT,
  ADD COLUMN IF NOT EXISTS consumo_id    TEXT,
  ADD COLUMN IF NOT EXISTS archivo_origen TEXT,
  ADD COLUMN IF NOT EXISTS created_at    TIMESTAMPTZ DEFAULT NOW();

-- 2) Convertir fecha_jornada a DATE si todavía es varchar
DO $$
DECLARE
  v_type TEXT;
BEGIN
  SELECT data_type INTO v_type
    FROM information_schema.columns
   WHERE table_name = 'comps_transacciones' AND column_name = 'fecha_jornada';
  IF v_type IN ('character varying','text') THEN
    -- Intento de cast: soporta YYYY-MM-DD y DD/MM/YYYY
    ALTER TABLE comps_transacciones
      ALTER COLUMN fecha_jornada TYPE DATE
      USING CASE
        WHEN fecha_jornada ~ '^\d{4}-\d{2}-\d{2}' THEN fecha_jornada::DATE
        WHEN fecha_jornada ~ '^\d{2}/\d{2}/\d{4}' THEN to_date(fecha_jornada,'DD/MM/YYYY')
        ELSE NULL
      END;
  END IF;
END $$;

-- 3) Backfill de comps_uid para filas existentes (si están vacías)
UPDATE comps_transacciones
   SET comps_uid = 'COMPS-' || to_char(fecha_jornada,'YYYYMMDD') || '-' || COALESCE(consumo_id,'') || '-' || COALESCE(cliente_id,'')
 WHERE comps_uid IS NULL AND fecha_jornada IS NOT NULL;

-- 4) PRIMARY KEY en id (si aún no existe)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'comps_transacciones'::regclass AND contype = 'p'
  ) THEN
    ALTER TABLE comps_transacciones ADD PRIMARY KEY (id);
  END IF;
END $$;

-- 5) UNIQUE en comps_uid (necesario para ON CONFLICT)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
     WHERE conrelid = 'comps_transacciones'::regclass
       AND contype = 'u'
       AND conname = 'comps_transacciones_comps_uid_key'
  ) THEN
    ALTER TABLE comps_transacciones
      ADD CONSTRAINT comps_transacciones_comps_uid_key UNIQUE (comps_uid);
  END IF;
END $$;

-- 6) Índice por fecha
CREATE INDEX IF NOT EXISTS idx_comps_jornada ON comps_transacciones (fecha_jornada);

COMMIT;
